# -*- coding: utf-8 -*-
"""MaximilianoOssa_PGY1121_009_D.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17iyUQXtrpLSGOtJSOMU66lLP3VXYMvXf
"""

import numpy as np
menu = True
opc = 0
nif = 0
nombre = 0
edad = 0
busq = 0

listanif = list()

while menu == True:
  print("--Bienvenido--")
  print("1. Guardar datos")
  print("2. Buscar datos")
  print("3. Imprimir certificado")
  print("4. Salir")

  try:
   opc = int(input("Escoja una opción del menu: "))
  except:
    print("Tipo de dato no valido. Volviendo al menú...")
    print("")
    continue

  if opc <1 or opc >4:
    print("Opción de número fuera de rango. Ingrese un numero entre 1 y 4 para escoger una opción del menú")
    print("")
    continue

  if opc == 1:
    print("Guardado de datos")
    nif = str(input("Ingrese su NIF. FORMATO XXXXXXXX-YYY. Incluya el guión: "))
    if len(nif) == 12:
      listanif.append(nif)
      print (listanif)
    else:
      print("Formato no valido")
    nombre = str(input("Ingrese su nombre: "))
    if len(nombre) >= 8:
      listanif.append(nombre)
      print (listanif)
    else:
      print("Su nombre debe tener minimo 8 caracteres.")
    edad = int(input("Ingrese su edad: "))
    if edad > 0:
      listanif.append(edad)
      print (listanif)
    else:
      print("Edad no válida.")
  if opc == 2:
    print("--Busqueda de datos--")
    busq = str(input("Ingrese el NIF a buscar. FORMATO XXXXXXXX-YYY. Incluya el guión: "))
    if busq == listanif[0]:
      print(f"Su NIF: {listanif[0]}")
      print(f"Nombre: {listanif[1]}")
      print(f"Edad: {listanif[2]}")
      print("Estos datos CORRESPONDEN a un ciudadano de la EU.")
    else:
      print("Este NIF no está en nuestros registros.")

  if opc == 3:
    print("Opc 3")

  if opc == 4:
    print(f"Saliendo del sistema. Hasta luego, {listanif[1]}")
    menu = False